### ISSUE TITLE
[Bug] 扩展较多时，只显示5个

### ISSUE THREAD

**Issue by SIPC** [rxliuli/secure-browse#1]
如题
ver:0.2.7
![image](https://github.com/rxliuli/secure-browse/assets/92251518/3244c829-5884-4cf5-9481-2c31d4178589)

**Comment by rxliuli** [comment]
> 如题 ver:0.2.7 ![image](https://private-user-images.githubusercontent.com/92251518/336873485-3244c829-5884-4cf5-9481-2c31d4178589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTc1NTMsIm5iZiI6MTcxNzU5NzI1MywicGF0aCI6Ii85MjI1MTUxOC8zMzY4NzM0ODUtMzI0NGM4MjktNTg4NC00Y2Y1LTk0ODEtMmMzMWQ0MTc4NTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE0MjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYWI3MWQ3MWE1NDVkNGIxYTJiYTkxN2U2ZGQxNWY2MDBjMWIzODU3YWY3NTFlYzM4ZDk1YjAzNjA5YzkzMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwTq_5-UY7dPaeua_G8ptYT9hWdwdgzbIbyk0c6TYUE)

这个列表显示了一些危险的扩展，具体来说是可以访问 http only cookie 的扩展，普通的扩展不关心你访问网站的 cookie，是安全的，因此并不显示在此处。
