### ISSUE TITLE
options to add website?

### ISSUE THREAD

**Issue by gutenye** [rxliuli/secure-browse#2]
Can I add custom websites myself?

**Comment by rxliuli** [comment]
Currently, it is not possible, but PRs adding new websites are welcome. You only need to modify `/entrypoints/background.ts`.

ref: https://github.com/rxliuli/secure-browse/blob/024bffdf438d360cbd1eeb7e576773fc809aa72e/entrypoints/background.ts#L27-L57

**Comment by gutenye** [comment]
thanks
