### ISSUE TITLE
How to prevent a malicious extension stealing cookie before you visit the site?

### ISSUE THREAD

**Issue by gutenye** [rxliuli/secure-browse#4]
Automatically disabling potentially unsafe extensions when visiting financial sites isn't very effective; a malicious extension can steal the site's cookies before you even navigate to the financial site. How to prevent this case?

**Comment by rxliuli** [comment]
There are only two possibilities for an extension to steal cookies:

1. Injecting a content script when visiting a website, which will be automatically disabled.
2. Stealing cookies through the `chrome.cookies` permission without visiting the website, which will be detected.

<img width="334" alt="image" src="https://github.com/rxliuli/secure-browse/assets/24560368/b552b088-2d25-4c12-95e4-1278fa7b427a">

**Comment by gutenye** [comment]
> Injecting a content script when visiting a website, which will be automatically disabled.

Javascript can't access the secure cookie, I'm sure Binance will mark the auth cookie as secure. https://stackoverflow.com/questions/72889905/how-can-i-read-httponly-and-secure-cookies-in-the-browser-with-javascript

Edit: JS can't access the HTTP Only cookie https://stackoverflow.com/questions/8064318/how-to-read-a-httponly-cookie-using-javascript

**Comment by rxliuli** [comment]
> > Injecting a content script when visiting a website, which will be automatically disabled.
> 
> Javascript can't access the secure cookie, I'm sure Binance will mark the auth cookie as secure. https://stackoverflow.com/questions/72889905/how-can-i-read-httponly-and-secure-cookies-in-the-browser-with-javascript
> 
> Edit: JS can't access the HTTP Only cookie https://stackoverflow.com/questions/8064318/how-to-read-a-httponly-cookie-using-javascript

Yes, I know about HttpOnly cookies, which is why I added the feature to detect extensions with the `chrome.cookies` permission.

**Comment by gutenye** [comment]
Got it, thanks.
